# versionは3系が最新版で、versionによって書き方が異なる
version: "3"
services:
  mysql:
    image: pekumirui/mysql:latest
    container_name: "mysqlapp"
    volumes:
      - initdata:/docker-entrypoint-initdb.d  #初期データをマウントする場所
      - mydata:/var/lib/mysql  #初期データをマウントする場所
    environment:
      - MYSQL_ROOT_PASSWORD=6539Eryu   #コンテナ内のMySQLを起動する際のパスワードを設定

volumes:
  initdata:
    driver: azure_file
    driver_opts:
      share_name: sql
      storage_account_name: stockdbmount
  mydata:
    driver: azure_file
    driver_opts:
      share_name: data
      storage_account_name: stockdbmount