# versionは3系が最新版で、versionによって書き方が異なる
version: "3"
services:
  mysql:
    build:
     context: .
     dockerfile: Dockerfile
    volumes:
      - ./DB:/docker-entrypoint-initdb.d  #初期データをマウントする場所
    image: original_mysql_world # イメージの名前
    environment:
      - MYSQL_ROOT_PASSWORD=6539Eryu   #コンテナ内のMySQLを起動する際のパスワードを設定