# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  branches:
    include:
    - main
  paths:
    include:
    - dockerfile/deloyment

resources:
  pipelines:
  - pipeline: doker-pull
    source: doker-pull
pool:
  name: Default

variables:
- name: subscription
  value: '9cc6ba70-2e1a-4749-b09e-630c9e071f42'
- name: rg-name
  value: 'rg-stock'

steps:
  - task: AzureResourceManagerTemplateDeployment@3
    inputs:
      deploymentScope: 'Resource Group'
      azureResourceManagerConnection: 'AzurePipeline'
      subscriptionId: $(subscription)
      action: 'Create Or Update Resource Group'
      resourceGroupName: $(rg-name)
      location: 'japaneast'
      templateLocation: 'URL of the file'
      csmFileLink: 'https://raw.githubusercontent.com/pekumirui/stock/deployment/deploy.json'
      deploymentMode: 'Incremental'
      deploymentName: 'deployment-arm'